services:
  bot:
    build:
      context: .
      dockerfile: packages/egg/Dockerfile
    depends_on: 
      - db
    restart: always
    env_file:
    - .env
    ports:
      - ${API_PORT}:9090
    volumes:
      - ./config:/app/config

  db:
    image: postgres
    restart: always
    env_file: 
      - .env
    volumes:
      - ./data/pg:/var/lib/postgresql/data