services:
  bot:
    build:
      context: .
      dockerfile: packages/egg/Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./packages/egg/src:/app/packages/egg/src
      - ./packages/egg/assets:/app/packages/egg/assets
      - ./packages/egg/node_modules/.prisma:/app/packages/egg/node_modules/.prisma
      - ./packages/egg/package.json:/app/packages/egg/package.json
      - ./packages/egg/tsconfig.json:/app/packages/egg/tsconfig.json
      - ./config:/app/config